###
POST http://127.0.0.1:2001/{{_id}}/start 
Content-Type: application/json

{}

###
POST http://127.0.0.1:2001/{{_id}}/stop 
Content-Type: application/json

{}


### Kirim pesan teks sederhana!
POST http://127.0.0.1:2001/{{_id}}/sendMessage 
Content-Type: application/json

{
    "jid": "{{jid}}",
    "content": {
        "text": "Kirim pesan"
    }
}