### Untuk mendapatkan keberadaan seseorang (apakah mereka mengetik atau online)
POST http://localhost:2000/api/whatsapp/6281938064470/presenceSubscribe 
Content-Type: application/json

{
    "toJid": "6281935155404@s.whatsapp.net"
}






### Ini memberi tahu orang/grup dengan ID apakah Anda online, offline, mengetik, dll.
POST http://localhost:2000/api/whatsapp/6281938064470/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "unavailable",
    "toJid": "6281935155404@s.whatsapp.net"
}

### Perbarui keberadaan menjadi tersedia
POST http://localhost:2000/api/whatsapp/6281938064470/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "available",
    "toJid": "6281935155404@s.whatsapp.net"
}

### Perbarui keberadaan menjadi sedang mengetik
POST http://localhost:2000/api/whatsapp/6281938064470/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "composing",
    "toJid": "6281935155404@s.whatsapp.net"
}

### Perbarui keberadaan menjadi sedang merekam
POST http://localhost:2000/api/whatsapp/6281938064470/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "recording",
    "toJid": "6281935155404@s.whatsapp.net"
}

### Perbarui keberadaan menjadi terjeda
POST http://localhost:2000/api/whatsapp/6281938064470/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "paused",
    "toJid": "6281935155404@s.whatsapp.net"
}
