### Untuk mendapatkan keberadaan seseorang (apakah mereka mengetik atau online)
POST http://localhost:2000/api/whatsapp/{{_id}}/presenceSubscribe 
Content-Type: application/json

{
    "toJid": "{{jid}}"
}






### Ini memberi tahu orang/grup dengan ID apakah Anda online, offline, mengetik, dll.
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "unavailable",
    "toJid": "{{jid}}"
}

### Perbarui keberadaan menjadi tersedia
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "available",
    "toJid": "{{jid}}"
}

### Perbarui keberadaan menjadi sedang mengetik
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "composing",
    "toJid": "{{jid}}"
}

### Perbarui keberadaan menjadi sedang merekam
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "recording",
    "toJid": "{{jid}}"
}

### Perbarui keberadaan menjadi terjeda
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate 
Content-Type: application/json

{
    "type": "paused",
    "toJid": "{{jid}}"
}
