### Kirim pesan teks sederhana!
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "Kirim pesan teks sederhana!"
    }
}

### Kirim pesan balasan
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "Kirim pesan balasan"
    },
    "options": {
        "quoted": {
            "key": {
                "remoteJid": "6281935155404@s.whatsapp.net",
                "fromMe": true,
                "id": "3EB0875D8B92CC3FF41B53"
            },
            "message": {
                "extendedTextMessage": {
                "text": "Kirim pesan teks sederhana!"
                }
            },
            "messageTimestamp": "1729520294",
            "status": "DELIVERY_ACK"
            }
    }
}

### Kirim pesan dengan mention
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "Kirim pesan dengan mention @adi",
        "mentions": [
            "{{jid2}}@s.whatsapp.net"
        ]
    }
}

### Kirim lokasi!
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "location": {
            "degreesLatitude": -8.2155165,
            "degreesLongitude": 111.0968846
        }
    }
}

### Kirim kontak!
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "contacts": {
            "displayName": "Ridho Prasetya",
            "contacts": [
                {
                    "vcard": "BEGIN:VCARD\nVERSION:3.0\nFN:Ridho Prasetya\nORG:Ndiing;\nTEL;type=CELL;type=VOICE;waid=6281935155404:+6281935155404\nEND:VCARD"
                }
            ]
        }
    }
}

### Kirim pesan reaksi
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "react": {
            "text": "💖",
            "key": {
                "remoteJid": "6281935155404@s.whatsapp.net",
                "fromMe": true,
                "id": "3EB0875D8B92CC3FF41B53"
            }
        }
    }
}
