@_id=6281938064XXX
@jid=6281953656XXX

### start
GET http://localhost:2000/api/whatsapp/{{_id}}/start

### stop
GET http://localhost:2000/api/whatsapp/{{_id}}/stop






### sendMessage
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "apa kabar ndiing? bisa pinjam dulu 100?"
    }
}

### sendMessage
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "apa kabar ndiing? bisa pinjam dulu 100?"
    },
    "options": {
        "quoted":  {
            "conversation": "wkwkwk",
            "messageContextInfo": {
                "deviceListMetadata": {
                    "senderKeyHash": "pQAlTN9J9K/pbg==",
                    "senderTimestamp": "1729480694",
                    "senderAccountType": "E2EE",
                    "receiverAccountType": "E2EE",
                    "recipientKeyHash": "SHzGndeGC0bJaw==",
                    "recipientTimestamp": "1726543726"
                },
                "deviceListMetadataVersion": 2,
                "messageSecret": "pPcrvvssQ0YdpJen3ABpLrtRQtOSsSe+C3Q4DLX/soo="
            }
        }
    }
}

### sendMessage
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "apa kabar ndiing? bisa pinjam dulu 100?",
        "mentions": [
            "6281953656221@s.whatsapp.net"
        ]
    }
}

### sendMessage
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "location": {
            "degreesLatitude": -8.2116608,
            "degreesLongitude": 111.1064576
        }
    }
}

### sendMessage
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "contacts": {
            "displayName": "Ridho Prasetya",
            "contacts": [
                {
                    "vcard": "BEGIN:VCARD\nVERSION:3.0\nFN:Ridho Prasetya\nORG:Ndiing;\nTEL;type=CELL;type=VOICE;waid=6281935155404:+6281935155404\nEND:VCARD"
                }
            ]
        }
    }
}

### sendMessage
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "react": {
            "text": "💖",
            "key": {
                "remoteJid": "6281953656221@s.whatsapp.net",
                "fromMe": false,
                "id": "3EB0F00F433E6FC482FF20"
            }
        }
    }
}







### readMessages
POST http://localhost:2000/api/whatsapp/{{_id}}/readMessages
Content-Type: application/json

{
    "keys": [
        {
            "remoteJid": "6281953656221@s.whatsapp.net",
            "fromMe": false,
            "id": "3EB0F00F433E6FC482FF20"
        }
    ]
}

### presenceSubscribe
POST http://localhost:2000/api/whatsapp/{{_id}}/presenceSubscribe
Content-Type: application/json

{
    "toJid": "{{jid}}@s.whatsapp.net"
}






### sendPresenceUpdate
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate
Content-Type: application/json

{
    "type": "composing",
    "toJid": "{{jid}}@s.whatsapp.net"
}

### sendPresenceUpdate
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate
Content-Type: application/json

{
    "type": "paused",
    "toJid": "{{jid}}@s.whatsapp.net"
}







### loadMessages
POST http://localhost:2000/api/whatsapp/{{_id}}/loadMessages
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

### loadMessage
POST http://localhost:2000/api/whatsapp/{{_id}}/loadMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net", 
    "id": "3EB0F00F433E6FC482FF20"
}