@_id=6281938064xxx
@jid=6281953656xxx

### start
GET http://localhost:2000/api/whatsapp/{{_id}}/start

### stop
GET http://localhost:2000/api/whatsapp/{{_id}}/stop






### sendMessage => Kirim teks sederhana
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "apa kabar ndiing? bisa pinjam dulu 100?"
    }
}

### sendMessage => Kirim pesan balasan
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "apa kabar ndiing? bisa pinjam dulu 100?"
    },
    "options": {
        "quoted":  {
            "conversation": "wkwkwk",
            "messageContextInfo": {
                "deviceListMetadata": {
                    "senderKeyHash": "pQAlTN9J9K/pbg==",
                    "senderTimestamp": "1729480694",
                    "senderAccountType": "E2EE",
                    "receiverAccountType": "E2EE",
                    "recipientKeyHash": "SHzGndeGC0bJaw==",
                    "recipientTimestamp": "1726543726"
                },
                "deviceListMetadataVersion": 2,
                "messageSecret": "pPcrvvssQ0YdpJen3ABpLrtRQtOSsSe+C3Q4DLX/soo="
            }
        }
    }
}

### sendMessage => Kirim pesan menyebutkan
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "text": "apa kabar ndiing? bisa pinjam dulu 100?",
        "mentions": [
            "6281953656221@s.whatsapp.net"
        ]
    }
}

### sendMessage => Kirim lokasi
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "location": {
            "degreesLatitude": -8.2116608,
            "degreesLongitude": 111.1064576
        }
    }
}

### sendMessage => Kirim kontak
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "contacts": {
            "displayName": "Ridho Prasetya",
            "contacts": [
                {
                    "vcard": "BEGIN:VCARD\nVERSION:3.0\nFN:Ridho Prasetya\nORG:Ndiing;\nTEL;type=CELL;type=VOICE;waid=6281935155404:+6281935155404\nEND:VCARD"
                }
            ]
        }
    }
}

### sendMessage => Pesan reaksi
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "react": {
            "text": "💖",
            "key": {
                "remoteJid": "6281953656221@s.whatsapp.net",
                "fromMe": false,
                "id": "3EB0F00F433E6FC482FF20"
            }
        }
    }
}

### sendMessage => Mengirim gif
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "video": "./media/video.mp4",
        "caption": "coba liat ini bro",
        "gifPlayback": true
    }
}

### sendMessage => Mengirim gif
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "video": "./media/video.mp4",
        "caption": "coba liat ini bro",
        "gifPlayback": true,
        "ptv": false
    }
}

### sendMessage => Kirim file audio
### mimetype=[audio/mp3,audio/mp4,audio/ogg]
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": {
        "audio": {
            "url": "./media/audio.mp3"
        },
        "mimetype": "audio/mp3"
    }
}

### sendMessage => Meneruskan pesan 
POST http://localhost:2000/api/whatsapp/{{_id}}/sendMessage
Content-Type: application/json

{
    "jid": "6281935155404@s.whatsapp.net",
    "content": {
        "forward": {
            "key": {
                "remoteJid": "6281953656221@s.whatsapp.net",
                "fromMe": false,
                "id": "3EB0F00F433E6FC482FF20"
            },
            "message": {
                "conversation": "wkwkwk",
                "messageContextInfo": {
                "deviceListMetadata": {
                    "senderKeyHash": "pQAlTN9J9K/pbg==",
                    "senderTimestamp": "1729480694",
                    "senderAccountType": "E2EE",
                    "receiverAccountType": "E2EE",
                    "recipientKeyHash": "SHzGndeGC0bJaw==",
                    "recipientTimestamp": "1726543726"
                },
                "deviceListMetadataVersion": 2,
                "messageSecret": "pPcrvvssQ0YdpJen3ABpLrtRQtOSsSe+C3Q4DLX/soo="
                }
            },
            "messageTimestamp": "1729481350",
            "status": "READ",
            "broadcast": false,
            "pushName": "Mokhamad Ariadi",
            "reactions": [
                {
                    "key": {
                        "remoteJid": "6281953656221@s.whatsapp.net",
                        "fromMe": true,
                        "id": "3EB05A05D71F370E70B7FB"
                    },
                    "text": "💖",
                    "senderTimestampMs": "1729482749113"
                }
            ]
        }
    }
}






### readMessages => Membaca pesan
POST http://localhost:2000/api/whatsapp/{{_id}}/readMessages
Content-Type: application/json

{
    "keys": [
        {
            "remoteJid": "6281953656221@s.whatsapp.net",
            "fromMe": false,
            "id": "3EB0F00F433E6FC482FF20"
        }
    ]
}

### presenceSubscribe
POST http://localhost:2000/api/whatsapp/{{_id}}/presenceSubscribe
Content-Type: application/json

{
    "toJid": "{{jid}}@s.whatsapp.net"
}






### sendPresenceUpdate => Perbarui keberadaan
### type=[unavailable,available,composing,recording,paused]
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate
Content-Type: application/json

{
    "type": "composing",
    "toJid": "{{jid}}@s.whatsapp.net"
}

### sendPresenceUpdate => Perbarui keberadaan
POST http://localhost:2000/api/whatsapp/{{_id}}/sendPresenceUpdate
Content-Type: application/json

{
    "type": "paused",
    "toJid": "{{jid}}@s.whatsapp.net"
}







### loadMessages
POST http://localhost:2000/api/whatsapp/{{_id}}/loadMessages
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

### loadMessage
POST http://localhost:2000/api/whatsapp/{{_id}}/loadMessage
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net", 
    "id": "3EB0F00F433E6FC482FF20"
}