###
POST http://localhost:2000/api/whatsapp/{{_id}}/start 
Content-Type: application/json

{}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/stop 
Content-Type: application/json

{}






###
POST http://localhost:2000/api/whatsapp/{{_id}}/query 
Content-Type: application/json

{
    "node": "",
    "timeoutMs": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/waitForSocketOpen 
Content-Type: application/json

{}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/sendNode 
Content-Type: application/json

{
    "frame": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/logout 
Content-Type: application/json

{
    "msg": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/end 
Content-Type: application/json

{
    "error": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/onUnexpectedError 
Content-Type: application/json

{
    "err": "",
    "msg": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/uploadPreKeys 
Content-Type: application/json

{
    "count": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/uploadPreKeysToServerIfRequired 
Content-Type: application/json

{}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/requestPairingCode 
Content-Type: application/json

{
    "phoneNumber": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/waitForConnectionUpdate 
Content-Type: application/json

{
    "check": "",
    "timeoutMs": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/sendWAMBuffer 
Content-Type: application/json

{
    "wamBuffer": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/fetchPrivacySettings 
Content-Type: application/json

{
    "force": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/appPatch 
Content-Type: application/json

{
    "patchCreate": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/profilePictureUrl 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "type": "",
    "timeoutMs": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/onWhatsApp 
Content-Type: application/json

{
    "jids": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/fetchBlocklist 
Content-Type: application/json

{}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/fetchStatus 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateProfilePicture 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "content": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/removeProfilePicture 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateProfileStatus 
Content-Type: application/json

{
    "status": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateProfileName 
Content-Type: application/json

{
    "name": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateBlockStatus 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "action": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateCallPrivacy 
Content-Type: application/json

{
    "value": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateLastSeenPrivacy 
Content-Type: application/json

{
    "value": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateOnlinePrivacy 
Content-Type: application/json

{
    "value": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateProfilePicturePrivacy 
Content-Type: application/json

{
    "value": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateStatusPrivacy 
Content-Type: application/json

{
    "value": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateReadReceiptsPrivacy 
Content-Type: application/json

{
    "value": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateGroupsAddPrivacy 
Content-Type: application/json

{
    "value": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/updateDefaultDisappearingMode 
Content-Type: application/json

{
    "duration": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/getBusinessProfile 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/resyncAppState 
Content-Type: application/json

{
    "args": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/cleanDirtyBits 
Content-Type: application/json

{
    "type": "",
    "fromTimestamp": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/addLabel 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "labels": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/addChatLabel 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "labelId": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/removeChatLabel 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "labelId": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/star 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "messages": "",
    "star": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupMetadata 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupCreate 
Content-Type: application/json

{
    "subject": "",
    "participants": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupLeave 
Content-Type: application/json

{
    "id": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupUpdateSubject 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "subject": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupRequestParticipantsList 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupRequestParticipantsUpdate 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "participants": "",
    "action": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupParticipantsUpdate 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "participants": "",
    "action": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupUpdateDescription 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "description": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupInviteCode 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupRevokeInvite 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupAcceptInvite 
Content-Type: application/json

{
    "code": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupRevokeInviteV4 
Content-Type: application/json

{
    "groupJid": "",
    "invitedJid": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupAcceptInviteV4 
Content-Type: application/json

{
    "args": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupGetInviteInfo 
Content-Type: application/json

{
    "code": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupToggleEphemeral 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "ephemeralExpiration": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupSettingUpdate 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "setting": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupMemberAddMode 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "mode": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupJoinApprovalMode 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "mode": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/groupFetchAllParticipating 
Content-Type: application/json

{}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/getPrivacyTokens 
Content-Type: application/json

{
    "jids": "{{jid}}@s.whatsapp.net"
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/assertSessions 
Content-Type: application/json

{
    "jids": "{{jid}}@s.whatsapp.net",
    "force": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/sendReceipt 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "participant": "",
    "messageIds": "",
    "type": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/sendReceipts 
Content-Type: application/json

{
    "keys": "",
    "type": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/refreshMediaConn 
Content-Type: application/json

{
    "forceGet": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/waUploadToServer 
Content-Type: application/json

{
    "stream": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/createParticipantNodes 
Content-Type: application/json

{
    "jids": "{{jid}}@s.whatsapp.net",
    "message": "",
    "extraAttrs": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/getUSyncDevices 
Content-Type: application/json

{
    "jids": "{{jid}}@s.whatsapp.net",
    "useCache": "",
    "ignoreZeroDevices": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/sendRetryRequest 
Content-Type: application/json

{
    "node": "",
    "forceIncludeKeys": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/rejectCall 
Content-Type: application/json

{
    "callId": "",
    "callFrom": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/requestPlaceholderResend 
Content-Type: application/json

{
    "messageKey": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/getOrderDetails 
Content-Type: application/json

{
    "orderId": "",
    "tokenBase64": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/getCatalog 
Content-Type: application/json

{
    "__namedParameters": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/getCollections 
Content-Type: application/json

{
    "jid": "{{jid}}@s.whatsapp.net",
    "limit": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/productCreate 
Content-Type: application/json

{
    "create": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/productDelete 
Content-Type: application/json

{
    "productIds": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/productUpdate 
Content-Type: application/json

{
    "productId": "",
    "update": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/register 
Content-Type: application/json

{
    "code": ""
}

###
POST http://localhost:2000/api/whatsapp/{{_id}}/requestRegistrationCode 
Content-Type: application/json

{
    "registrationOptions": ""
}

