### Untuk memeriksa apakah ID yang diberikan ada di WhatsApp
POST http://localhost:2000/api/whatsapp/6281938064470/onWhatsApp 
Content-Type: application/json

{
    "jids": "6281935155404@s.whatsapp.net"
}


### Untuk mendapatkan status seseorang
POST http://localhost:2000/api/whatsapp/6281938064470/fetchStatus 
Content-Type: application/json

{
    "jid": "6281935155404@s.whatsapp.net"
}


### Untuk mengubah status profil Anda
POST http://localhost:2000/api/whatsapp/6281938064470/updateProfileStatus 
Content-Type: application/json

{
    "status": "Ada"
}


### Untuk mengubah nama profil Anda
POST http://localhost:2000/api/whatsapp/6281938064470/updateProfileName 
Content-Type: application/json

{
    "name": "Ndiing"
}


### Untuk mendapatkan foto profil seseorang/kelompok, untuk gambar resolusi rendah
POST http://localhost:2000/api/whatsapp/6281938064470/profilePictureUrl 
Content-Type: application/json

{
    "jid": "6281935155404@s.whatsapp.net"
}


### Untuk gambar resolusi tinggi
POST http://localhost:2000/api/whatsapp/6281938064470/profilePictureUrl 
Content-Type: application/json

{
    "jid": "6281935155404@s.whatsapp.net",
    "type": "image"
}


### Untuk mengubah foto profil Anda atau kelompok
POST http://localhost:2000/api/whatsapp/6281938064470/updateProfilePicture 
Content-Type: application/json

{
    "jid": "6281935155404@s.whatsapp.net",
    "content": { "url": "./content.jpeg" }
}


### Untuk menghapus foto profil Anda atau kelompok
POST http://localhost:2000/api/whatsapp/6281938064470/removeProfilePicture 
Content-Type: application/json

{
    "jid": "6281935155404@s.whatsapp.net"
}


### Untuk memblokir atau membuka blokir pengguna
POST http://localhost:2000/api/whatsapp/6281938064470/updateBlockStatus 
Content-Type: application/json

{
    "jid": "6281953656221@s.whatsapp.net",
    "action": "block"
}


### Untuk membuka blokir pengguna
POST http://localhost:2000/api/whatsapp/6281938064470/updateBlockStatus 
Content-Type: application/json

{
    "jid": "6281953656221@s.whatsapp.net",
    "action": "unblock"
}


### Untuk mendapatkan profil bisnis, seperti deskripsi atau kategori
POST http://localhost:2000/api/whatsapp/6281938064470/getBusinessProfile 
Content-Type: application/json

{
    "jid": "6281953656221@s.whatsapp.net"
}
