### Untuk membuat grup
POST http://localhost:2000/api/whatsapp/6281938064470/groupCreate 
Content-Type: application/json

{
    "subject": "grup",
    "participants": [
        "6281935155404@s.whatsapp.net",
        "6281953656221@s.whatsapp.net"
    ]
}






### Untuk menambah/menghapus orang ke grup atau menurunkan/menaikkan pangkat orang
POST http://localhost:2000/api/whatsapp/6281938064470/groupParticipantsUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "participants": [
        "6281953656221@s.whatsapp.net"
    ],
    "action": "add"
}

### 
POST http://localhost:2000/api/whatsapp/6281938064470/groupParticipantsUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "participants": [
        "6281953656221@s.whatsapp.net"
    ],
    "action": "remove"
}

### 
POST http://localhost:2000/api/whatsapp/6281938064470/groupParticipantsUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "participants": [
        "6281935155404@s.whatsapp.net"
    ],
    "action": "demote"
}

### 
POST http://localhost:2000/api/whatsapp/6281938064470/groupParticipantsUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "participants": [
        "6281935155404@s.whatsapp.net"
    ],
    "action": "promote"
}






### Untuk mengubah subjek grup
POST http://localhost:2000/api/whatsapp/6281938064470/groupUpdateSubject 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "subject": "subjek grup"
}

### Untuk mengubah deskripsi grup
POST http://localhost:2000/api/whatsapp/6281938064470/groupUpdateDescription 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "description": "deskripsi grup"
}






### Untuk mengubah pengaturan grup, hanya izinkan admin untuk mengirim pesan
POST http://localhost:2000/api/whatsapp/6281938064470/groupSettingUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "setting": "announcement"
}

### Izinkan semua orang untuk mengirim pesan
POST http://localhost:2000/api/whatsapp/6281938064470/groupSettingUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "setting": "not_announcement"
}

### Izinkan semua orang untuk mengubah pengaturan grup -- seperti foto profil, dll.
POST http://localhost:2000/api/whatsapp/6281938064470/groupSettingUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "setting": "unlocked"
}

### Hanya izinkan admin untuk mengubah pengaturan grup
POST http://localhost:2000/api/whatsapp/6281938064470/groupSettingUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "setting": "locked"
}






### Untuk keluar dari grup
POST http://localhost:2000/api/whatsapp/6281938064470/groupLeave 
Content-Type: application/json

{
    "id": "120363348813803535@g.us"
}

### Untuk mendapatkan kode undangan untuk grup
POST http://localhost:2000/api/whatsapp/6281938064470/groupInviteCode 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us"
}

### Untuk mencabut kode undangan dalam grup
POST http://localhost:2000/api/whatsapp/6281938064470/groupRevokeInvite 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us"
}

### Untuk menanyakan metadata grup
POST http://localhost:2000/api/whatsapp/6281938064470/groupMetadata 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us"
}

### Untuk bergabung dengan grup menggunakan kode undangan
POST http://localhost:2000/api/whatsapp/6281938064470/groupAcceptInvite 
Content-Type: application/json

{
    "code": "IIgu8UNodjb0Ey8E4IAwSc"
}

### Untuk mendapatkan info grup berdasarkan kode undangan
POST http://localhost:2000/api/whatsapp/6281938064470/groupGetInviteInfo 
Content-Type: application/json

{
    "code": "IIgu8UNodjb0Ey8E4IAwSc"
}

# ### Untuk bergabung dengan grup menggunakan groupInviteMessage
# POST http://localhost:2000/api/whatsapp/6281938064470/groupAcceptInviteV4 
# Content-Type: application/json

# {
#     "args": ""
# }

### Untuk mendapatkan daftar permintaan bergabung
POST http://localhost:2000/api/whatsapp/6281938064470/groupRequestParticipantsList 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us"
}






### Untuk menyetujui/menggagalkan permintaan bergabung
POST http://localhost:2000/api/whatsapp/6281938064470/groupRequestParticipantsUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "participants": [
        
    ],
    "action": "approve"
}


### Untuk menyetujui/menggagalkan permintaan bergabung
POST http://localhost:2000/api/whatsapp/6281938064470/groupRequestParticipantsUpdate 
Content-Type: application/json

{
    "jid": "120363348813803535@g.us",
    "participants": [
        
    ],
    "action": "reject"
}





